# Generated by Django 2.2.5 on 2019-10-01 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='venue',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
    ]
