# Generated by Django 2.2 on 2019-11-14 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventFinderApp', '0003_auto_20191113_1434'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='userimages/')),
            ],
        ),
        migrations.AddField(
            model_name='category',
            name='images',
            field=models.ManyToManyField(null=True, related_name='Category', to='eventFinderApp.Images'),
        ),
    ]
